version: 0.6.4-{build}

environment:
  RUBYGEMS_TOKEN:
    secure: JMYgDTDQLMo9n9iqe+z18TKdsWhHdaSzJB/BeWbxfD6efzXzYK6K59XzAKX5jFseQetL0RCrk+gE9WQrT6OTcg==
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_TOKEN:
    secure: cu6NcEUU479Jdkyf/qSduY/JwjsSQ8hkKZHB79UC/VY8alk1iUB1cWoBIl+Zl+Um

image:
  - Visual Studio 2022
  - Ubuntu

for:
  -
      matrix:
        only:
          - image: Visual Studio 2022

      artifacts:
        - path: '*.exe'

      install:
        - tzutil /s "W. Europe Standard Time"
        - gem install bundler
        - bundle install

      build_script:
        - bundle exec rake buildsingle
        - rake buildexe

      test_script:
        - bundle exec rake test
        - bundle exec rake testsingle
        - bundle exec rake testexe

  -
      matrix:
        only:
          - image: Ubuntu

      artifacts:
        - path: '*.rb'
        - path: '*.gem'

      install:
        - export TZ=Europe/Berlin
        - rvm use 2.7.8
        - bundle install

      build_script:
        - bundle exec rake buildsingle
        - bundle exec rake buildgem

      test_script:
        - COVERALLS_REPO_TOKEN=${COVERALLS_TOKEN} bundle exec rspec spec/test_default.rb
        - bundle exec rake testsingle

      before_deploy:
        - sh: "mkdir ~/.gem && echo -e \"---\n:rubygems_api_key: ${RUBYGEMS_TOKEN}\" > ~/.gem/credentials"
        - chmod 0600 ~/.gem/credentials
        - gem push *.gem

before_build:
  - ruby -v
  - gem -v
  - bundle -v
  - bundle exec rake check

deploy:
  - provider: GitHub
    auth_token:
      # expires early 2025
      # create API key in github and encrypt here: https://ci.appveyor.com/tools/encrypt
      secure: 4YJ0a92H3pQi1rv704FuV/l4Dy1mn5fDf536xY6QkL7r7l3LGHbaqldXO7mXvoLB/NlX19DXUggx7NlneUm3Bp/RYJPhYlduh1RI8nJH49/ul8pueVpZ9Y18CorNZAUu
    artifact: /.*\.(?:gem|exe|rb)/
    draft: true
    on:
      APPVEYOR_REPO_TAG: true
